### ISSUE TITLE
Wycinanie szczątek

### ISSUE THREAD

**Issue by barrinek** [eldakar/ttng#10]
Wycinanie/wyrywanie szczątek z ciała.

Najpierw skrypt liczy ilość ciał, później leci po kolei wycinać.

Wycinasz .... z ciała .... powinno odpalac wycinanie nastepnych szczatek

**Comment by eldakar** [comment]
@yavi liczenie cial juz jest, trzeba przepisac na event i registrantow

wycinanie musi byc w petli, jest to legalne tylko jesli zrobimy statyczny delay
