### ISSUE TITLE
quickbind na wstawanie

### ISSUE THREAD

**Issue by dojii** [eldakar/ttng#118]
![image](https://user-images.githubusercontent.com/31402997/73031065-62373800-3e3b-11ea-8bd2-dd6964d17e96.png)

poprosze binda pod quickbinda, najlepiej z dzwoneczkiem

**Comment by eldakar** [comment]
* dodalem dzwoneczek do 'czerwonych quickbindow' 
* zrobilem wstawanie jako czerwony bind
