### ISSUE TITLE
Siadanie w knajpach

### ISSUE THREAD

**Issue by barrinek** [eldakar/ttng#12]
Bindowanie siadania - zamow jedzenie,

A moze najpierw gdzies usiadziesz?                                                                              

wybiera stolik z ponizszych:

Gdzie chcesz usiasc? Przy debowym stoliku, przy drugim debowym stoliku, przy trzecim debowym stoliku, przy czwartym debowym stoliku czy przy piatym debowym stoliku?

**Comment by eldakar** [comment]
@mishiaq 
ogarnij:
-  /help QuickBind  
-  bundles/QuickBind
-  komenda qb
