### ISSUE TITLE
Brakujące kody klawiszy przy łączeniu się przez putty

### ISSUE THREAD

**Issue by dojii** [eldakar/ttng#130]
Hej, jak rozmawialiśmy na discordzie jak się łącze przez shell i mam w putty VT100+ to klawisze na numeryku inaczej się zachowują.
Kierunkowe są ok ale już / * - + DEL mają inne kody niż przy tym windowsowym TT
i teraz tak na czystym tt niezależnie czy jest num lock wlaczony klawisze poszczegolne zachowują się następujaco 
>
/ /
* *
- -
+ \eOl
DEL \eOn
I nie można ich zmakrowac przez /conf
<

**Comment by eldakar** [comment]
hey 
\eOn jest juz w konfie

dodalem \eOl
