### ISSUE TITLE
Możliwość dodania do konfiguracji pochwa backpack

### ISSUE THREAD

**Issue by dojii** [eldakar/ttng#139]
możliwość wrzucenia w konfigurację opcji to co jest ustawione jako plecak, jeśli postać walczy kilkoma rodzajami broni to może raz latać z młotem raz z toporem i wtedy raczej nie nosi ze sobą wszystkiego tylko trzyma w plecaku, jeśli w opcjach by się dało
/conf pochwa plecak
to przy użyciu aliasu dbb i obb alias wrzucałby i wyciągał broń z plecaka, jaka? pierwszą, to już by sobie gracz musiał pilnować, jeśli postać by walczyła dwiema brońmi to wtedy ustawia w 
/conf pochwa2 plecak i dbb wyciaga dwie bronie i dobywa dobyciem zwodu

**Comment by eldakar** [comment]
dziala to chyba juz tak jak mowilismy nie?
