### ISSUE TITLE
zmienna lampa_switch

### ISSUE THREAD

**Issue by dojii** [eldakar/ttng#141]
zmienna która działa jako zapal lampe, jesli raz sie jej uzyje zmienia sie na zgas lampe, i potem wraca do domyslnego ustawienia zapal lampe
Po co to?
chce sobie pod jeden klawisz wsadzic zapalanie i gaszenie lampy, teraz mam to pod dwoma

**Comment by eldakar** [comment]
masz nowa komende `/lampa`
nie ma to nic wspolnego z dopelnianiem!
