### ISSUE TITLE
Dodanie podpowiedzi do bindow wyswietlanych przez echo.

### ISSUE THREAD

**Issue by MutantMonx** [eldakar/ttng#143]
Dodanie podpowiedzi do bindow w stylu mudleta np:

**********************************
        Bijesz innego: CTRL + W
**********************************

**********************************
       Cel ataku: CTRL + 1
**********************************

itd

**Comment by eldakar** [comment]
moge to napisac tylko jesli mi dasz przyklad kazdego typu, nie bede robil ogolnego bo bedzie spam

**Comment by eldakar** [comment]
wont fix
