### ISSUE TITLE
Dodanie raportowania zmeczenia prowadzacemu (alias)

### ISSUE THREAD

**Issue by MutantMonx** [eldakar/ttng#146]
Dodanie raportowania zmeczenia prowadzacemu bez wzgledu na poziom zmeczenia  (alias)

**Comment by eldakar** [comment]
Dodalem komende /zme
Dodalem tez raportowanie do prowadzacego - przy jakiejkolwiek zmianie (nie tylko od bardzo zmeczonego)
```
#alias {/zme$} {
	#if {"$duch[$avatarid][team]" == "true"} {
		szepnij ob_$team_lead_id $zmeczenie[$charstate[fatigue]];
	} {
		#line ignore #sh {Nie jestes w zadnej druzynie.};
	};
} {1};
```
