### ISSUE TITLE
Dodanie licznika postępów z podziałem dziennie i globalnie

### ISSUE THREAD

**Issue by MutantMonx** [eldakar/ttng#148]
Dodanie licznika postępów na zasadzie /postepy2 (daty chronologicznie)
[data] - nieboty + jakies
[data] - zadowalajace
[data] - nieduze
-----------------------
Łącznie: 10,8 niebotów tj. xxx nieznaków.

**Comment by eldakar** [comment]
komenda `/conf globalnypostep <wartosc>` ustawia licznik, od ktorego zacznie naliczac postepy
dodam do aktualnej komendy `/kills` wyswietlenie tej wartosci, i podzielenie przez 16 zeby pokazalo ile niebotow wbitych.

**Comment by eldakar** [comment]
<img width="345" alt="Screenshot 2020-04-18 at 08 49 47" src="https://user-images.githubusercontent.com/11772152/79631506-b3607a80-8151-11ea-8659-5cdbc4457faa.png">
