### ISSUE TITLE
Bind ponownego dobycia broni po wytraceniu

### ISSUE THREAD

**Issue by barrinek** [eldakar/ttng#15]
jw.

**Comment by barrinek** [comment]
Bol w prawej/lewej dloni czuje sie mniej odczuwalny.

**Comment by yavi** [comment]
Bol w {prawej|lewej} dloni staje sie mniej odczuwalny.

Uderzenie jest tak silne, ze bezwiednie puszczasz %bron%.

**Comment by yavi** [comment]
Dodane "dobadz broni" na quickbindzie.
