### ISSUE TITLE
Zmiana koloru pasków stanu na czerwony w miarę ubywania

### ISSUE THREAD

**Issue by MutantMonx** [eldakar/ttng#168]
Zmiana koloru pasków HP i STAMINA na kolor czerwony od ZŁEJ KONDYCJI i WYCZERPANY.

Można RANNY dać pomarańczowy, bardzo zmeczony też.

**Comment by eldakar** [comment]
dodalem HP nie dodam raczej zmeczenia
naprawilem tez te [ ] nawiasy w /conf pasek mini, dookola hp
