### ISSUE TITLE
MAGIC - stun z tarczy barona

### ISSUE THREAD

**Issue by dojii** [eldakar/ttng#176]
Blekitno-srebrna trojkatna tarcza rozblyskuje nagle bardzo ostrym blekitnym swiatlem, skierowanym w strone paskudnego wscieklego ryboczleka!

**Comment by eldakar** [comment]
dobra, wyglada mi to na pierwsza osobe,

dodam jeszcze z trzeciej osoby 'tarcza trzymana przez %* rozblyskuje'
