### ISSUE TITLE
brakujące spece korka 1os 

### ISSUE THREAD

**Issue by ardberg** [eldakar/ttng#178]
te co złapałem narazie (uwaga na spacje musiałem wyciąć ręcznie mapę łapane z telefonu) 

Powolnym wypadem do przodu atakujesz szybkiego zlotookiego zwierzoczleka dzgajac go swoja poreczna dluga szabla,lecz niedogodna pozycja nie pozwala ci na zbyt silny cios i zadajesz tylko nieznaczne obrazenia.

Zgrabnym ruchem unikasz ciosu okrutnego czarnego zwierzoczleka i korzystajac z dogodnej pozycji rabiesz go na odlew swoja poreczna dluga szabla, gleboko rozrywajac jego cialo

**Comment by eldakar** [comment]
pierwszy punkt naprawiony

drugi siedzi tu gdzies
#action {{Blyskawicznym polobrotem unikasz ciosu|Niezgrabnym ruchem unikasz ciosu|Oszczednym ruchem unikasz ciosu|Plynnym ruchem unikasz ciosu|Plynnym wypadem w przod atakujesz|Powolnym wypadem do przodu|Powolnym ruchem unikasz ciosu|Zgrabnym ruchem unikasz ciosu|Zgrabnym wypadem do przodu atakujesz|Oszczednym wypadem do przodu atakujesz|Blyskawicznym wypadem do przodu atakujesz|Niezgrabnym wypadem do przodu probujesz zaskoczyc} %*gleboko rozyrwajac%*} {collect KS 4 $AVATAR_NAME;#line gag}{2};

**Comment by eldakar** [comment]
rozyrwajac
typo jest
