### ISSUE TITLE
przemykanie

### ISSUE THREAD

**Issue by dojii** [eldakar/ttng#18]
czy jest szansa by po wcisnieciu konfiguracji przycisków np. lewy cntr + kierunek na num padzie było przemykanie? luba jakiś przełącznik tego jak zachowują się klawisze na numpadzie

**Comment by eldakar** [comment]
@dojii 
wklej mi kody klawiszy ktore odpowiadaja control + kierunki

**Comment by dojii** [comment]
niestety po kombinacji control + kierunek żadne kody się nie pojawiają więc nie mam co wkleić

**Comment by eldakar** [comment]
w miedzyczasie dodalem przemykanie pod kierunkami z shiftem N,E,W,S,D itp
