### ISSUE TITLE
brakujace ciosy korka z 1ej osoby

### ISSUE THREAD

**Issue by dojii** [eldakar/ttng#180]
Zgrabnym wypadem do przodu atakujesz wysoka cuchnaca mumie i korzystajac z zaskoczenia dzgasz ja mocno swym egzotycznym jadeitowym palaszem (wpraw kamien), gleboko wbijajac 
sie w jej cialo.

**Comment by eldakar** [comment]
bylo typo "gleboka wbijajac" --> "gleboko wbijajac"
