### ISSUE TITLE
system /destroy 

### ISSUE THREAD

**Issue by ardberg** [eldakar/ttng#181]
komenda system - /destroy
nie działa poprawnie - Android

**Comment by eldakar** [comment]
komenda system odswieza zapisana wartosc ostatniej apki (musi byc conajmniej jeden pokoj dodany z /a)
jesli nowa wartosc 'swiata istnieje' z system jest mniejsza niz zapisana, wtedy wyswietla sie sugestia */destroy*
/destroy usuwa wszystkie pokoje dodane przez /a i przez /rysuj (dynamiczne kolorowanie labiryntow)

sprawdz jeszcze raz
