### ISSUE TITLE
_zbieraj_ nie łapie zombi + błąd w specu Kg 

### ISSUE THREAD

**Issue by ardberg** [eldakar/ttng#191]
siema

zombi jak umiera ma inną linijkę i bind nie łapie zbierania (also - spec kończący kg ma 4/6)

![Screenshot_20200602_233149](https://user-images.githubusercontent.com/63424797/83635123-9534c980-a59b-11ea-8fbc-0b6407df836d.jpg)

**Comment by eldakar** [comment]
Po roku zamkniete :D
