### ISSUE TITLE
[_trybchodzenie_ kompas] przestaje działać, gdy wybierze błędny kierunek.

### ISSUE THREAD

**Issue by ghost** [eldakar/ttng#195]
Gdy w trybie kompasu wybierze się przez przypadek kierunek którego nie ma na mapie i zostanie zwrócny komunikat o braku wyjścia, to kolejne lokacje wybierane są bez sprawdzenia kompasu.
```
Ukladasz urzadzenie na wyprostowanej dloni i przez pare chwil wstrzymujesz oddech, by pozwolic kompasowi pokazac kierunek polnocny. Uwaznie przygladasz sie ulozeniu wskazowki i na jej podstawie ustalasz pozostale kierunki swiata.

gora
Nie widzisz zadnego wyjscia prowadzacego na gore.

wespnij sie na gore
Zaczynasz wspinac sie na gore.
Z latwoscia pniesz sie w gore.
Docierasz na gore.


     K


Na bagniskach.



     K


Na bagniskach.
```

**Comment by eldakar** [comment]
to tak nie dziala, 
jesli klepiesz wyjscie niestandardowe z palca, to skrypt nie wie ze ma uruchomic kompas

niestety, kazde wejscie na gore/dol mozna wykonac wiecej niz jedna komenda, jesli dana komenda ktorej uzyles nie jest dodana jako *oficjalne* wejscie na gore, to kupa.

takze musisz uzywac numeryka lub kierunkow standardowych, zeby kompas dzialal :)
