### ISSUE TITLE
Ocena tarcz, broni, zbroi w oddzielnym oknie

### ISSUE THREAD

**Issue by thaerro** [eldakar/ttng#21]
Czy można prosić o wykonanie oceny sprzętu w jakimś oddzielnym okienku?
Dziękuję.

**Comment by eldakar** [comment]
moge zrobic tak jak jest komenda sp:
otwiera sie popup na mapce i w tym samym miejscu gdzie dlugi opis lokacji jest skrocona ocena sprzetu. 
podczas odswiezenia mapy (ruch udany/nieudany) okienko zniknie - takze jesli oceniasz cos biegnac - bedziesz mial pewnie malo czasu na wglad.
moze byc tak?

**Comment by thaerro** [comment]
Można spróbować, aby tak było. Zobaczymy jak się to będzie sprawowało.
