### ISSUE TITLE
Komenda /kills - pokazuje  godziny wbicia postępów. Nie pokazuje ile zajęło wbicie konkretnego postępu np. 15 min 30 sek.

### ISSUE THREAD

**Issue by werrg** [eldakar/ttng#212]
Komenda do oceny kamieni + zsumowania wartości w MTH/Złocie/srebrze/miedzi

**Comment by eldakar** [comment]
pierwsza wersja 

mozna juz sprawdzac czy dziala pod komenda `#var expo` w polu [epoc]
