### ISSUE TITLE
Button pokazujący otrzymaną pocztę - do czasu odebrania świeci się. Podczas expa można przeoczyć ze przyszedł list

### ISSUE THREAD

**Issue by werrg** [eldakar/ttng#213]
Komenda do oceny kamieni + zsumowania wartości w MTH/Złocie/srebrze/miedzi

**Comment by eldakar** [comment]
po otrzymaniu notyfikacji o poczcie, zacznie migac co 2 sekundy na mapie czerwony przycisk POCZTA

aby go wyciszyc trzeba wpisac `/p`
