### ISSUE TITLE
Dodanie opcji kolorowania mobów na expowiskach.

### ISSUE THREAD

**Issue by ctarx** [eldakar/ttng#222]
Przykładowo dla zc/puch

`krasnolud[a-z]* chaosu`
`zwierzoczlek[a-z]*`
`troll[a-z]*`
`bykocentaur[a-z]*`
`hobgoblin[a-z]*`
`lansjer[a-z]*`
`krasnozwierz[a-z]*`

oraz jakieś wyróżnienie dla:

`((W|w)ladczy) .* krasnolud chaosu`
`((D|d)ostojny) .* krasnolud chaosu`
`((D|d)umny) .* krasnolud chaosu`
`((P|p)owazny) .* krasnolud chaosu`

Koncepcja jest taka, że kolorowanie można wlączać aliasem lub automatycznie dla danego expowiska.

**Comment by eldakar** [comment]
"potezny",
    "rogaty",
    "gigantyczny",
    "ogromny",
    "gargantuiczny",
    "przerazajacy",
    "muskularny",
    "umiesniony"

**Comment by ctarx** [comment]
"partyzanci" nie nadpisuja priorytetu i sa nadal kolorowani jak reszta mobow.
