### ISSUE TITLE
"Literki" przy osobach na lokacji.

### ISSUE THREAD

**Issue by thaerro** [eldakar/ttng#23]
Swego czasu byly literki przypiyswane odpowienio koljenym osobom na lokacji. 
Nie widzę teraz ich w oknie "kondycji".

![](https://cdn.discordapp.com/attachments/606772775096680472/649448041841164288/unknown.png)

![](https://cdn.discordapp.com/attachments/606772775096680472/649459941643386889/unknown.png)

**Comment by eldakar** [comment]
naprawione
