### ISSUE TITLE
dodac opcje /powtorzenter w pasek 

### ISSUE THREAD

**Issue by ardberg** [eldakar/ttng#230]
Jest wolny slot miejsce w "rozne" 
obok BRO LAM PLA mozna dodac ENT (?) powtorz enter wlaczony/wylaczony

![image](https://user-images.githubusercontent.com/63424797/120095973-d1ecbf80-c120-11eb-8af0-c8f7e3929247.png)

**Comment by eldakar** [comment]
![image](https://user-images.githubusercontent.com/11772152/120682697-a9ecbb80-c494-11eb-8498-63fcbe1e0802.png)
