### ISSUE TITLE
Poprawka do ciosow specjalnych barbarzyncy

### ISSUE THREAD

**Issue by ctarx** [eldakar/ttng#239]
`#action {Nie %* walisz %* na odlew %*, kaleczac %*.} {collect OK 1 $AVATAR_NAME;#line gag};`
`#action {Nie %* walisz %* na odlew %*, tlukac %*.} {collect OK 3 $AVATAR_NAME;#line gag};`

`#action {Nie %* walisz %* na odlew %*, kaleczac %*. Nieprzyjemne} {collect OK_OGLUCH 1 $AVATAR_NAME;#line gag} {1};`
`#action {Nie %* walisz %* na odlew %*, tlukac %*. Nieprzyjemne} {collect OK_OGLUCH 3 $AVATAR_NAME;#line gag} {1};`

---
#nop SPECE OK Z PIERWSZEJ OSOBY;
`#nop action {{Nie tracac czasu na zbedne manewry|Nie przebierajac w srodkach|Nie zastanawiajac sie dlugo|Nie silac sie na wirtuozerie} z calej sily walisz %* kaleczac} {collect OK 1 $AVATAR_NAME;#line gag} {1};`

`#nop action {{Nie tracac czasu na zbedne manewry|Nie przebierajac w srodkach|Nie zastanawiajac sie dlugo|Nie silac sie na wirtuozerie} z calej sily walisz %* tlukac} {collect OK 3 $AVATAR_NAME;#line gag} {1};`

---
#nop SPECE OK Z TRZECIEJ OSOBY;
`#action {{Nie tracac czasu na zbedne manewry|Nie przebierajac w srodkach|Nie zastanawiajac sie dlugo|Nie silac sie na wirtuozerie} %* z calej sily wali %* kaleczac} {collect OK 1 %2;#line gag};`

`#action {{Nie tracac czasu na zbedne manewry|Nie przebierajac w srodkach|Nie zastanawiajac sie dlugo|Nie silac sie na wirtuozerie} %* z calej sily wali %* tlukac} {collect OK 3 %2;#line gag};`

**Comment by eldakar** [comment]
merge zrobiony, ale nie jest to pelna poprawka - brakuje poprawki ciosow z ogluchem
