### ISSUE TITLE
Bindowanie pod jakis klawisz formy

### ISSUE THREAD

**Issue by thaerro** [eldakar/ttng#25]
Fajne i przydane byłoby jak by w momencie spadku kondycji do Ledwo zywego/ciężko rannego pod jakiś klawisz (edytowalny) F(1-10) na przykład bindowała się komenda +kondycja.

**Comment by eldakar** [comment]
pod quickbind?

**Comment by thaerro** [comment]
no wlasnie moze nie
jakis inny

**Comment by eldakar** [comment]
czy widzisz ten przycisk uzywany do czegos jeszcze innego, skoro odchodzimy od quickbindu?
moze zgeneralizujemy ten ticket i sie zajmiemy caloscia

**Comment by thaerro** [comment]
Chciałem zastosować inny przycisk, bo quickbind może być potrzebny po coś innego w danym momencie.  Dlatego propozycja, aby dodawanie +kondycja +zmęczenie było pod innym klawiszem.
