### ISSUE TITLE
Nie dzialaja bindy pod rybki

### ISSUE THREAD

**Issue by mishiaq** [eldakar/ttng#26]
Po ustawieniu rybek, nie wchodza bindy. Pojawiaja sie tylko w linii komend kody klawiszy:
F1 - 
![image](https://user-images.githubusercontent.com/57958173/70032374-a6c9f400-15ad-11ea-869c-3a75d269ba66.png)

F2 -
![image](https://user-images.githubusercontent.com/57958173/70032398-b47f7980-15ad-11ea-9829-a0cf8132a03f.png)

Zweryfikowane pod putty i mRemoteNG

**Comment by mishiaq** [comment]
Nie, nie. Reopen. 
W momencie w ktorym rybki bierze, nie podbindowuje sie zaciecie ryby na wedce.

**Comment by eldakar** [comment]
po ostatnich zmianiach w /conf Mac** trzeba caly Fishing przepisac...

**Comment by mishiaq** [comment]
Imho wystarczyłoby tylko pod quick binda podbijać. Skoro teraz wszystkie klawisze funkcyjne sa do dyspozycji gracza (nie zostały dynamiczne podbindowywane pierwsze kilka F-ów i np. F12), to obstawiam ze komus moglyby sie skonczyc wolne przyciski, a nadpisywac komus w configu to niefajne.

**Comment by dojii** [comment]
![image](https://user-images.githubusercontent.com/31402997/71541720-ac70ea80-295d-11ea-959d-69c9485a185c.png)
Taki coś na Tefie miałem, nieskomplikowane, sprawdzało się idealnie, oczywiście nie wiem jak to przepisać na TT fast_bind to quickbind

**Comment by eldakar** [comment]
i tak to tez zrobilem, quickbindy dwa
