### ISSUE TITLE
bind (moze nie quickbind) na +K przy okreslonej kondycji 

### ISSUE THREAD

**Issue by ardberg** [eldakar/ttng#262]
JEst na mudlecie i jest super, 
ustawiasz np "w zlej" i jak jestes w zlej dostajesz echo na ekran z bindem na +K 
przydatne - raz na idloexpie wywali ci jak kondycja Ci spadam dwa szybko mozesz lyknac jak trzeba

**Comment by eldakar** [comment]
ok, nie bede hardcodowal klawiszy jak w mudlecie :). moge to zrobic tak:
1. wiadomosc na ekranie przy danym stanie kondycji, podobnie jak jest przy zmeczneiu (`/conf meldujprzy`)
2. robisz sobie makro na +k , jak chcesz dodatkowy klawisz to napisz
3. moge dac 'custom message' w powiadomieniu z punktu 1. jesli naprzykald chcesz zeby twoj klawisz sie tam znajdowal

**Comment by eldakar** [comment]
`/conf alertkondycja <integer>`
`/conf alertkondycjateskt tekst moze byc ze spacjami`

![image](https://user-images.githubusercontent.com/11772152/121504239-c3808c80-c9d9-11eb-9026-b537eb9adcdd.png)
