### ISSUE TITLE
info binda na dylizans (in / out ) 

### ISSUE THREAD

**Issue by ardberg** [eldakar/ttng#296]
jest stary styl, nie jak inne quick bindy "button"

![image](https://user-images.githubusercontent.com/63424797/122810216-00485f80-d2c7-11eb-88b4-426721aa1129.png)

**Comment by eldakar** [comment]
![image](https://user-images.githubusercontent.com/11772152/122879360-b6945f00-d330-11eb-91b4-173ef12e9d9e.png)
