### ISSUE TITLE
Szeptanie/Meldowanie zmeczenia prowadzącemu.

### ISSUE THREAD

**Issue by thaerro** [eldakar/ttng#31]
Przydało by się takie coś:
Prowadzący drużynę pyta nas o zmęczenie.

a my aliasem /bindem sprawdzamy stan i szeptem mrowimy mu jakie jest.

**Comment by eldakar** [comment]
bindem przy zmianie zmeczenia, zaczynajac od 'bardzo zmeczony' ?

**Comment by thaerro** [comment]
no może być - chyba :)

**Comment by eldakar** [comment]
trzeba przetestowac!
