### ISSUE TITLE
Obsługa Statków

### ISSUE THREAD

**Issue by thaerro** [eldakar/ttng#32]
Prośba o zrobienie obsługi pływania statkami korsarskimi.
Bindowanie portu, bindowanie nabrzeża.

**Comment by eldakar** [comment]
1. aliasy do plywania na dostepne porty
2. dynamiczne aliasy na cumowanie

**Comment by eldakar** [comment]
3. #action {Drakkar doplywa do celu swojej podrozy.}  - triggeruje sprawdzenie portow i nabrzezy
