### ISSUE TITLE
Możliwość bindowania klawiszy na klawiaturze numerycznej

### ISSUE THREAD

**Issue by dojii** [eldakar/ttng#52]
Dzień dobry, 

Chciałbym poprosić o dołożenie do konfiguracji (/conf) możliwości konfigurowania klawiszy na klawiaturze numerycznej dla:
+- \e01 - nie wiem czy to zero czy litera o
DEL - \e0n
Nie wiem czy jeszcze byłoby możliwe to samo z / * - na numerycznej bo one nie dają kodu zwrotnego.

**Comment by eldakar** [comment]
ja tez nie wiem czy to zero czy o.
otworz czystego tintina (komenda tt++) i wklej mi tu te kody

**Comment by dojii** [comment]
+ - \eOl
DEL - \eOn

**Comment by dojii** [comment]
7 \eOw
8 \eOx
9 \eOy
4 \eOt
5 \eOu
6 \eOv
1 \eOq
2 \eOr
3 \eOs
DEL \eOn
PLUS  \eOl

To są wszystkie możliwe klawisze do bindowania na ustawianieu klawiatury VT100+

**Comment by eldakar** [comment]
#var KEY_PAD_DEL {\eOn};
#var KEY_PAD_PLUS {\eOl};
