### ISSUE TITLE
Alias dbb

### ISSUE THREAD

**Issue by dojii** [eldakar/ttng#55]
Dzień dobry, 
Alias dbb dobywa broni z pochwy/uprzezy, jednak jeśli tej broni w danym pojemniku nie mamy to nic nie dobędzie, mam w związku z tym dwa pomysły:
- jeśli alias nie dobywa broni z pochwy to dobywa broń z ekwipunku - czasem ktoś wytrąci, kowal nam odda broń (obb chowa wyłącznie dobytą broń), lub z jakiegoś powodu nie będziemy jej mieć dobytej ale będzie w ekwipunku
- wyskakuje powiadomienie, że nie dobyło się broni - jeśli nie ma w ekwipunku ani w pojemniku, nie wiem, sprzedałeś u pasera na ten przykład z rozpędu

**Comment by eldakar** [comment]
moge zrobic cos takiego:
trigger { alez kunsztowna uprzaz jest pusta ... } {
quickbind -> dobadz broni
}

**Comment by dojii** [comment]
no to już by pomogło
