### ISSUE TITLE
Alias - por - porównywanie cech z celem

### ISSUE THREAD

**Issue by dojii** [eldakar/ttng#57]
Dzień dobry,

Poproszę o alias np. por do porównywania cech z celem na zasadzie:
- jeśli wpiszę samo por to porówna mi cechy z aktualnym przeciwnikiem
- jeśli wpiszę por elfem/arnvaldem/etc. to porówna mi ze wskazanym celem
Alias miałby porównywać wszystkie cechy
Efekt porównania może być wyświetlany w formie jakiejś tabelki czy pasków to jak już się żywnie podoba, byle czytelnie ;p

**Comment by eldakar** [comment]
komenda 
/por - porownuje z celem ataku
/por * - porownuje z *
