### ISSUE TITLE
Przerobić panel informacyjny STAN

### ISSUE THREAD

**Issue by dojii** [eldakar/ttng#58]
![image](https://user-images.githubusercontent.com/31402997/71513550-170d2200-289b-11ea-9715-2425ee61cd18.png)

**Comment by eldakar** [comment]
<img width="144" alt="Screenshot 2019-12-28 at 17 47 53" src="https://user-images.githubusercontent.com/11772152/71547620-2de66e00-299a-11ea-9936-c5915323410a.png">
