### ISSUE TITLE
Ciosy magika - jatagan

### ISSUE THREAD

**Issue by dojii** [eldakar/ttng#66]
Zniknęła numeracja z ciosów magika, wygląda jakby się coś nie wyświetlało bo jest lekko przesunięta linijka
![image](https://user-images.githubusercontent.com/31402997/71583912-a7a06800-2b10-11ea-828a-a84a6b513659.png)

**Comment by eldakar** [comment]
co znaczy zniknela? 
i co jest lekko przesuniete, nie widze na tym screenshocie

**Comment by eldakar** [comment]
ok widze

**Comment by eldakar** [comment]
fixed
