### ISSUE TITLE
Wartości domyślne konfiguracji

### ISSUE THREAD

**Issue by yavi** [eldakar/ttng#9]
CombatMacrosConfigAttackCommand zabij
CombatMacrosConfigAttackFlags z

Do tego proponowałbym jeszcze:
QuickBindMacroKey tylda

Rzeczy powinny działać "out of the box" :)

**Comment by barrinek** [comment]
Powinno również wyświetlać, że nie ma takiej opcji w przypadku np gildii, zawodów itp (nie wiadomo jak wpisać, czy GL, czy gladiator, czy gl) :)

**Comment by eldakar** [comment]
> Powinno również wyświetlać, że nie ma takiej opcji w przypadku np gildii, zawodów itp (nie wiadomo jak wpisać, czy GL, czy gladiator, czy gl) :)

Jesli dana opcja nie istnieje, pojawia sie komunikat
W nowym manualu, dodalem wszystkie wartosci dostepne. Nie planuje robic testu czy dana wartosc jest obsluzona - poprostu dana komenda zostanie zignorowana.

**Comment by eldakar** [comment]
Nie zrobie defaulta na quickbind, poniewaz tylda moze byc uzywana przez inny skrypt.
Nie planuje tez robic macro managera, ktory bedzie sprawdzal ktore klawisze sa w uzyciu.

reszta gotowa ;)
