### ISSUE TITLE
Kolorowanie NPCY

### ISSUE THREAD

**Issue by thaerro** [eldakar/ttng#90]
tych trzeba pokolorowac - to banda taka. :)

Wszawy jednooki mezczyzna - BOSS
Krzywozeby masywny mezczyzna
Kaprawy koscisty mezczyzna

**Comment by eldakar** [comment]
@thaerro [sam](https://github.com/eldakar/ttng/wiki/Baza---Aliasy) sobie to mozesz zrobic :)

> /baza_dodaj <gildia> <trzyczlonowy opis> <imie> - dodaj do bazy postac o opisie opis i imieniu imie z przynaleznoscia do gildii gildia

```
/baza_dodaj BOSS wszawy jednooki mezczyzna ZebrakSzef
/baza_dodaj NPC krzywozeby masywny mezczyzna ZebrakJeden
/baza_dodaj NPC kaprawy koscisty mezczyzna ZebrakDwa
```

a potem dajesz

`/baza_update`

**Comment by thaerro** [comment]
PlayerDB: Od teraz Bandakrzywegoszef z opisem wszawy jednooki mezczyzna nalezy do BOSS
PlayerDB: Od teraz Bandakrzywego1 z opisem krzywozeby masywny mezczyzna nalezy do NPC 
PlayerDB: Od teraz Bandakrzywego2 z opisem kaprawy koscisty mezczyzna nalezy do NPC  

/baza_update                           
PlayerDB: Odswiezam definicje postaci. 
PlayerDB: Zaladowane.                  

Dobrze?

**Comment by eldakar** [comment]
dobrze
