### ISSUE TITLE
Pokorowac brakujace magiki

### ISSUE THREAD

**Issue by eldakar** [eldakar/ttng#91]

**Comment by thaerro** [comment]
snieznobialy luskowy pancerz

**Comment by thaerro** [comment]
egzotyczny jadeitowy palasz

**Comment by eldakar** [comment]
> snieznobialy luskowy pancerz

dodany

> egzotyczny jadeitowy palasz

dodany

**Comment by eldakar** [comment]
zrobione, kolejne nalezy dodawac pojedynczo - albo wg manuala z WIKI
