### ISSUE TITLE
Zioła - ususzony przelot - leczenie trądu - przezucie

### ISSUE THREAD

**Issue by thaerro** [eldakar/ttng#95]
Dodaj do aliasów z ziołami proszę drugie działanie ususzonego przelotu - **odtrutka na trąd.**

```
Czujesz sie znacznie lepiej.
Przezuwasz kremowy owlosiony ususzony kwiat (Przelot zm- mana-).
```

`**KOMENDA**: przezuj`

**Comment by thaerro** [comment]
**Zarażenie - z sarkofagu w Campogrotta.** - Jak się źle przeszuka - **NIE MOŻNA** przeszukiwać sarkofagu!

```
Zaczynasz przeszukiwac zamkniety sarkofag.

Zdaje ci sie ze poczules lekkie uklucie w dlon.
```

**Objawy:** między innymi:
```
Drapiesz sie nagle w glowe.
Czujesz sie nieswojo.
Czujesz ze twoje cialo roztacza intensywny swad zgnilizny.
Na rozpalonym czole Thaera perli sie zimny pot.
```

**Comment by eldakar** [comment]
nie zamykam tego bo mi sie przyda
dodalem ususzony przelot do aliasow 

tak sie dodaje nowe wlasciwosci w pliki Herbs/content.tin
#var zioladb[Przelot_][sposob][o] {przezuj};

Przelot_ oznacza ususzony
